# Generated by Django 4.1.7 on 2023-09-08 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostmanBasket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('ttl', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PostmanAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('errors', models.JSONField(default=list)),
                ('notifications', models.BooleanField(default=True)),
                ('percent_full', models.FloatField()),
                ('baskets', models.ManyToManyField(related_name='postman_accounts', to='apistart.postmanbasket')),
            ],
        ),
    ]
