# Generated by Django 4.1.7 on 2023-09-08 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apistart', '0002_alter_postmanaccount_errors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmanaccount',
            name='baskets',
            field=models.ManyToManyField(blank=True, related_name='postman_accounts', to='apistart.postmanbasket'),
        ),
    ]
