# Generated by Django 4.1.7 on 2023-09-08 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apistart', '0003_alter_postmanaccount_baskets'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pantry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('key_value_store', models.JSONField(default=dict)),
            ],
        ),
        migrations.RenameModel(
            old_name='PostmanBasket',
            new_name='Basket',
        ),
        migrations.DeleteModel(
            name='PostmanAccount',
        ),
        migrations.AddField(
            model_name='pantry',
            name='basket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pantries', to='apistart.basket'),
        ),
    ]
